### ISSUE TITLE
Add i18n for RBP Support Strings

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/psp-scheduled-notifications#17]
Even if there's no changes to the strings, your plugin should still define these. That causes the translation to be local to your plugin rather than using the default ones in RBP Support which will make more sense to volunteer translators. 

You can copy the Array of strings from the README and just swap in your Text Domain via a Search/Replace.

**Comment by brashrebel** [comment]
That's a good plan and I'll do that. Thanks. I'd note though, that volunteer translators are rare and almost non-existent for niche, commercial plugins like this. But we may pursue getting translations done in the future.

**Comment by d4mation** [comment]
Yeah, I don't expect any translations to happen really. But it would be best if the translations for those Strings were in the plugin's `.pot` file :+1
